"""Tests for config.py -> config.toml conversion and config precedence"""

import os
import time
from pathlib import Path
from unittest.mock import patch

try:
    import tomllib
except ModuleNotFoundError:  # Python < 3.11
    import tomli as tomllib
from click.testing import CliRunner

from revelation.cli import cli
from revelation.config import Config
from revelation.convert_config import config_to_toml, convert_config

PY_CONFIG = '''
REVEAL_META = {"title": "T", "author": "A", "description": "D"}
REVEAL_SLIDE_SEPARATOR = "---"
REVEAL_VERTICAL_SLIDE_SEPARATOR = "--"
REVEAL_THEME = "heig_ec+g"
REVEAL_THEME_LOGO = "gte"
REVEAL_LICENCE = "by-sa"
REVEAL_TEMPLATE = "myPresentation.html"
REVEAL_CONFIG = {"width": 2056, "height": 1320, "controls": True}
'''

# Layout produced by convertconfig before the fix: top-level keys written
# after [reveal_meta], so TOML puts them inside that table.
OLD_LAYOUT_TOML = '''
[reveal_meta]
title = "T"
author = "A"
description = "D"

reveal_licence = "by-sa"
reveal_template = "myPresentation.html"
reveal_theme = "heig_ec+g"
reveal_theme_logo = "gte"

[reveal_config]
width = 2056
'''


def test_simple_keys_written_before_tables(tmp_path):
    py = tmp_path / "config.py"
    py.write_text(PY_CONFIG)
    toml_file = tmp_path / "config.toml"
    assert convert_config(py, toml_file)

    data = tomllib.loads(toml_file.read_text())
    assert data["reveal_theme_logo"] == "gte"
    assert data["reveal_template"] == "myPresentation.html"
    assert "reveal_theme_logo" not in data["reveal_meta"]
    assert data["reveal_meta"] == {"title": "T", "author": "A", "description": "D"}
    assert data["reveal_config"]["width"] == 2056


def test_converted_file_loads_like_python(tmp_path):
    py = tmp_path / "config.py"
    py.write_text(PY_CONFIG)
    toml_file = tmp_path / "config.toml"
    assert convert_config(py, toml_file)

    from_toml = Config(str(toml_file))
    for key in ("REVEAL_THEME", "REVEAL_THEME_LOGO", "REVEAL_LICENCE",
                "REVEAL_TEMPLATE", "REVEAL_META", "REVEAL_CONFIG"):
        assert key in from_toml
    assert from_toml["REVEAL_THEME_LOGO"] == "gte"
    assert from_toml["REVEAL_META"] == {"title": "T", "author": "A", "description": "D"}


def test_old_layout_still_loads(tmp_path):
    """Files generated by the previous converter keep working"""
    toml_file = tmp_path / "config.toml"
    toml_file.write_text(OLD_LAYOUT_TOML)

    config = Config(str(toml_file))
    assert config["REVEAL_THEME_LOGO"] == "gte"
    assert config["REVEAL_LICENCE"] == "by-sa"
    assert config["REVEAL_TEMPLATE"] == "myPresentation.html"
    assert config["REVEAL_META"] == {"title": "T", "author": "A", "description": "D"}


def test_config_to_toml_no_table_before_simple_key():
    text = config_to_toml({"REVEAL_META": {"title": "T"}, "REVEAL_THEME": "x"})
    lines = [line for line in text.splitlines() if line and not line.startswith("#")]
    assert lines.index('reveal_theme = "x"') < lines.index("[reveal_meta]")


def _make_presentation(tmp_path, py_newer):
    (tmp_path / "slides.md").write_text("# Test")
    py = tmp_path / "config.py"
    toml_file = tmp_path / "config.toml"
    py.write_text(PY_CONFIG)
    toml_file.write_text('reveal_theme = "white"\n')
    now = time.time()
    old, new = now - 100, now
    os.utime(py, (new, new) if py_newer else (old, old))
    os.utime(toml_file, (old, old) if py_newer else (new, new))
    return tmp_path


def _start(path):
    with patch("revelation.cli.os.path.exists", return_value=True), \
            patch("revelation.cli.WebSocketServer"):
        return CliRunner().invoke(cli, ["start", str(path), "--no-browser"])


def test_warning_when_py_config_newer(tmp_path):
    result = _start(_make_presentation(tmp_path, py_newer=True))
    assert result.exit_code == 0, result.output
    assert "is newer than" in result.output
    assert "convertconfig" in result.output


def test_no_warning_when_toml_newer(tmp_path):
    result = _start(_make_presentation(tmp_path, py_newer=False))
    assert result.exit_code == 0, result.output
    assert "is newer than" not in result.output


def test_no_warning_when_py_newer_but_identical(tmp_path):
    """config.py saved after an identical config.toml: nothing is ignored"""
    _make_presentation(tmp_path, py_newer=True)
    assert convert_config(tmp_path / "config.py", tmp_path / "config.toml", force=True)
    later = time.time() + 10
    os.utime(tmp_path / "config.py", (later, later))
    result = _start(tmp_path)
    assert result.exit_code == 0, result.output
    assert "is newer than" not in result.output


def test_no_prompt_when_stdin_not_a_tty(tmp_path):
    """A python-only config must not block a non-interactive start"""
    (tmp_path / "slides.md").write_text("# Test")
    (tmp_path / "config.py").write_text(PY_CONFIG)
    with patch("revelation.cli.click.confirm") as mock_confirm:
        result = _start(tmp_path)
    assert result.exit_code == 0, result.output
    mock_confirm.assert_not_called()
    assert not (tmp_path / "config.toml").exists()
